# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.workspace:
        class: AppBundle\Admin\WorkspaceAdmin
        arguments: [~, AppBundle\Entity\Workspace, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Workspace }
    admin.project:
        class: AppBundle\Admin\ProjectAdmin
        arguments: [~, AppBundle\Entity\Project, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Project }
    mava_user.profile.form.type:
        class: AppBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: mava_user_profile }

    fos_user.entity_manager:
        alias: fos_user.object_manager
    notifier.listener:
       class: AppBundle\EventListener\Notifier
       tags:
         - { name: doctrine.event_listener, event: postPersist }